/**
 * Oracle-harness voor @nvag/contract-tests.
 * Env-gated: draait alleen wanneer NVAG_TEST_ORACLE_URL is gezet
 * (bijv. oracledb://user:pass@host:1521/XEPDB1).
 */

import type { ConnectionConfig } from '@nvag/contracts'
import type { ProviderContractHarness } from '@nvag/contract-tests'
import { createOracleProvider } from '../src/index'

export function getOracleTestConfig(): ConnectionConfig | null {
  const url = process.env.NVAG_TEST_ORACLE_URL
  if (!url) return null
  try {
    const u = new URL(url)
    return {
      id: 'contract-oracle',
      name: 'contract',
      providerId: 'oracle',
      environment: 'TEST',
      host: u.hostname,
      port: Number(u.port || 1521),
      database: u.pathname.replace(/^\//, '') || 'XEPDB1',
      username: decodeURIComponent(u.username || 'system'),
      auth: 'username-password',
      ssl: { mode: 'disable' },
      connectionTimeoutMs: 10000,
      group: 'Contract'
    }
  } catch {
    return null
  }
}

export function createOracleHarness(cfg: ConnectionConfig): ProviderContractHarness {
  return {
    name: 'oracle',
    dialect: 'oracle',
    createProvider: () => createOracleProvider(),
    createConfig: () => cfg,
    fixtureSql: `
      CREATE TABLE contract_dml (id NUMBER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR2(100) NOT NULL, CONSTRAINT pk_contract_dml PRIMARY KEY (id));
      INSERT INTO contract_dml (name) VALUES ('a');
      INSERT INTO contract_dml (name) VALUES ('b');
      INSERT INTO contract_dml (name) VALUES ('c');
      CREATE TABLE contract_meta (id NUMBER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR2(100) NOT NULL, email VARCHAR2(255), active NUMBER(1) DEFAULT 1 NOT NULL, CONSTRAINT pk_contract_meta PRIMARY KEY (id));
      INSERT INTO contract_meta (name, email, active) VALUES ('Alice', 'alice@x.nl', 1);
      INSERT INTO contract_meta (name, email, active) VALUES ('Bob', 'bob@x.nl', 0);
    `,
    quoteIdentifier: (name) => `"${name.replace(/"/g, '""')}"`,
    dmlTable: 'CONTRACT_DML',
    metadataTable: 'CONTRACT_META',
    metadataTableColumns: ['ID', 'NAME', 'EMAIL', 'ACTIVE'],
    makeLimitQuery: (table, n) => `SELECT * FROM ${table} FETCH FIRST ${n} ROWS ONLY`,
    schema: (cfg.database ?? '').toUpperCase(),
    multipleStatements: 'reject',
    skips: { errorPosition: true }
  }
}
